missing file from a link in README.md
but its still messing the correct value for starkPrivateKey
if i send it like this node returns 

ReferenceError: starkPrivKey is not defined.

if i declare  "const starkPrivKey = ethPrivKey"   i get

"error":"ETH_STARKKEY_NOT_MATCHED" .

opened an issue about this.

i'm using infura on a local node, balance and history are ok